name: CI

on:
  pull_request:
  push:

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.13.1.0"
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    needs: fourmolu
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.10"]
        ghc: ["9.2.8", "9.4.5", "9.6.2"]

    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'


      - uses: haskell/actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
          cabal freeze

      - uses: actions/cache/restore@v3
        name: Cache ~/.cabal/store and dist-newstyle
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build
        run: |
          cabal build all

      - name: Test
        run: |
          AUTH_TOKEN=${{ steps.auth.outputs.access_token }}
          cabal test all

      - name: Haddock
        run: |
          cabal haddock
        if: ${{ matrix.ghc != '9.2.8' }}

      - name: Save cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
